version: '3.8'
services:

  server_weather:
    build: ./server
    container_name: server_weather_container
    working_dir: /server
    build:
      context: ./server
      dockerfile: ./Dockerfile
    volumes:
      - ./server
    env_file:
      - ./server/.env.server.development
    ports:
      - "9000:9000"

  weather_information:
    build: ./client
    container_name: weather_information
    working_dir: /app
    build:
      context: ./
      dockerfile: ./infra/dev/Dockerfile
    volumes:
      - ./:/app
    env_file:
      - ./.env.development
    ports:
      - "3000:3000"
    links:
      - server_weather
